import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';

import { ViewTransitions } from 'next-view-transitions';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { Modals } from '@/components/Modal';
import { Providers } from '@/components/Providers';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body
          className={cn(
            'bg-background min-h-screen font-sans antialiased',
            inter.variable
          )}
        >
          <Providers>
            <Header />
            <Modals />
            {children}
            <Footer />
          </Providers>
        </body>
      </html>
    </ViewTransitions>
  );
}
